import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Award, CheckCircle2, Shield } from "lucide-react";
import { motion } from "framer-motion";

const accreditations = [
  // TODO: Add these accreditations when certificates are available
  // {
  //   id: 1,
  //   title: "80G Certification",
  //   issuer: "Income Tax Department, Government of India",
  //   year: "2020",
  //   description: "Tax exemption certificate enabling donors to claim tax deductions on their contributions.",
  //   icon: Shield
  // },
  // {
  //   id: 2,
  //   title: "12A Registration",
  //   issuer: "Income Tax Department, Government of India",
  //   year: "2020",
  //   description: "Registration certificate for tax exemption on income generated by the foundation.",
  //   icon: Award
  // },
  // {
  //   id: 3,
  //   title: "FCRA Registration",
  //   issuer: "Ministry of Home Affairs",
  //   year: "2021",
  //   description: "Authorization to receive foreign contributions for social development projects.",
  //   icon: CheckCircle2
  // },
  // {
  //   id: 4,
  //   title: "CSR-1 Registration",
  //   issuer: "Ministry of Corporate Affairs",
  //   year: "2021",
  //   description: "Registered as eligible entity for Corporate Social Responsibility funding.",
  //   icon: Award
  // },
  {
    id: 5,
    title: "NGO Darpan Registration",
    issuer: "NITI Aayog",
    description: "Wings of Wisdom Foundation® is registered under the Darpan as a NGO. The organization has gone through several scrutiny to get associated with the Darpan platform. The NGO-DARPAN started out as an initiative of the Prime Minister's Office, to create and promote a healthy partnership between VOs/NGOs and the Government of India. The Portal is managed at present by NITI Aayog.",
    icon: Shield
  },
  {
    id: 6,
    title: "GuideStar India Certification",
    issuer: "GuideStar India",
    description: "Wings of Wisdom Foundation® has acquired the certification by providing all the necessary compliances to the GuideStar India. Under its certification programme, GuideStar India validates NGOs based on their legal and financial compliance, as well as on their level of public disclosure of information. NGOs opt for certification levels based on their interest and capacity for transparency and public disclosure.",
    icon: CheckCircle2
  },
  {
    id: 7,
    title: "Benevity Causes Portal",
    issuer: "Benevity",
    description: "Wings of Wisdom Foundation® is registered with the Benevity causes portal, which is trusted by non-profits and causes globally to power and deliver meaningful and impactful programming. It helps improve the way causes access and become eligible for corporate giving programs and modernizes how they process and receive donation funds.",
    icon: Award
  }
];

const Accreditations = () => {
  return (
    <main className="min-h-screen bg-background">
      <section className="bg-primary py-20">
        <div className="container mx-auto px-4">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-center"
          >
            <h1 className="text-4xl md:text-5xl font-bold text-primary-foreground mb-4">
              Accreditations & Certifications
            </h1>
            <p className="text-lg text-primary-foreground/90 max-w-2xl mx-auto">
              Our commitment to transparency, accountability, and compliance with regulatory standards
            </p>
          </motion.div>
        </div>
      </section>

      <section className="py-16">
        <div className="container mx-auto px-4">
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {accreditations.map((accreditation, index) => {
              const Icon = accreditation.icon;
              return (
                <motion.div
                  key={accreditation.id}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5, delay: index * 0.1 }}
                >
                  <Card className="h-full hover:shadow-lg transition-shadow">
                    <CardHeader>
                      <div className="flex items-start justify-between mb-4">
                        <div className="h-12 w-12 rounded-full bg-primary/10 flex items-center justify-center">
                          <Icon className="h-6 w-6 text-primary" />
                        </div>
                      </div>
                      <CardTitle className="text-xl">{accreditation.title}</CardTitle>
                      <CardDescription className="font-medium">
                        {accreditation.issuer}
                      </CardDescription>
                    </CardHeader>
                    <CardContent>
                      <p className="text-muted-foreground">{accreditation.description}</p>
                    </CardContent>
                  </Card>
                </motion.div>
              );
            })}
          </div>

          <div className="mt-16 bg-muted/50 rounded-lg p-8">
            <h2 className="text-2xl font-bold mb-4 text-center">Why Accreditations Matter</h2>
            <div className="grid md:grid-cols-3 gap-6 mt-8">
              <div className="text-center">
                <Shield className="h-10 w-10 text-primary mx-auto mb-3" />
                <h3 className="font-semibold mb-2">Trust & Credibility</h3>
                <p className="text-sm text-muted-foreground">
                  Official recognition ensures donors can trust our operations
                </p>
              </div>
              <div className="text-center">
                <CheckCircle2 className="h-10 w-10 text-secondary mx-auto mb-3" />
                <h3 className="font-semibold mb-2">Compliance</h3>
                <p className="text-sm text-muted-foreground">
                  Adherence to all legal and regulatory requirements
                </p>
              </div>
              <div className="text-center">
                <Award className="h-10 w-10 text-accent mx-auto mb-3" />
                <h3 className="font-semibold mb-2">Transparency</h3>
                <p className="text-sm text-muted-foreground">
                  Public accountability and open financial reporting
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
};

export default Accreditations;
